name: JMeter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'  # Use 'temurin' for OpenJDK

    - name: Install JMeter
      run: |
        wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.4.1.tgz
        tar -xzf apache-jmeter-5.4.1.tgz
        sudo mv apache-jmeter-5.4.1 /opt/jmeter
        echo "/opt/jmeter/bin" >> $GITHUB_PATH

    - name: Run JMeter Test
      run: |
        cd /opt/jmeter/bin
        ./jmeter -n -t LoadTest/perfomance.jmx-l results.jtl
        

    - name: Upload JMeter Results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: results.jtl