name: Run JMeter Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install JMeter
      run: |
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
        tar -xvzf apache-jmeter-5.5.tgz
        sudo mv apache-jmeter-5.5 /opt/apache-jmeter-5.5
        export PATH=$PATH:/opt/apache-jmeter-5.5/bin

    - name: Verify JMeter Installation
      run: |
        jmeter -v

    - name: Run JMeter Tests
      run: |
        jmeter -n -t LoadTest/perfomance.jmx -l results.jtl

    - name: Archive Test Results
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-results
        path: results.jtl
