name: JMeter Test

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.4.1.tgz
          tar -xzf apache-jmeter-5.4.1.tgz
          sudo mv apache-jmeter-5.4.1 /opt/jmeter
          echo "export PATH=$PATH:/opt/jmeter/bin" >> $GITHUB_ENV

      - name: Run JMeter Test
        run: |
          jmeter -n -t path/to/your/test.jmx -l results.jtl
          # Replace 'path/to/your/test.jmx' with the actual path to your JMX file

      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: results.jtl